### ISSUE TITLE
.deb package missing

### ISSUE THREAD

**Issue by ghost** [Gigoteur/UnicornConsole#22]
where can we find .deb packages?

**Comment by hallucino** [comment]
Good question ! Right now I'm waiting to finish the 0.0.3 version before doing that.

**Comment by doyousketch2** [comment]
It's easy enough to build from source, but takes some time.

Be certain to install dev headers for OpenSSL or you get this error:  
> error: failed to run custom build command for `openssl-sys v0.9.15`  

So yeah, either run each command individually, or string them all together with `&&`  

`sudo apt-get update`  
`sudo apt-get install libsdl2-dev libsdl2-mixer-dev libpython3-dev libssl1.0-dev`  
`git clone https://github.com/Gigoteur/PX8.git`  
`cd PX8`  
`cargo build --features="cpython px8_plugin_lua" --release`  
`cd target/release`  
`./px8`
