### ISSUE TITLE
Loading Celeste (pico-8)

### ISSUE THREAD

**Issue by vanfanel** [Gigoteur/UnicornConsole#62]
Hi, Gigoteur!

I have found that PX8 is, with a LARGE difference, the best fantasy-console available on the Raspberry PI 3 in terms of performance: picolove is slooooow and buggy, for example, and your implementation is perfectly synchronized with the screen: smooth scrolls are smooth!
So I would REALLY love to use it to load Pico-8 games, too. However, Celeste, one of the first classics I tried from the Pico-8 (https://www.lexaloffle.com/bbs/?tid=2145), does not load ("Failed to load the cartidge").
Is there any possibility to run that game? I tried the "-m pico8" parameter with no luck...

Thanks!

**Comment by hallucino** [comment]
Thank you

Running Celeste could be really interesting but I will need to fix all features to have the compatibility with pico8 (memory access etc) and the lua language modification too

But it is doable in the future !

**Comment by vanfanel** [comment]
I hope to see it soon... It has potential to become the best pico8 implementation available. The original pico8 has "pauses" on the Pi I can't diagnose because of the lack of sourcecode,

**Comment by egordorichev** [comment]
Hey, @hallucino, I could implement RAM, because I had big experience with that in the past time. But the thing is, your loader is really old now, and it doesn't properly load new carts (ver 9). It just gets stuck in a while loop.

Implementing RAM will mean much more faster access to VRAM also.

**Comment by hallucino** [comment]
Hi, yes you're probably right but for this cart https://www.lexaloffle.com/bbs/cposts/1/15133.p8.png it seems still ok.

Feel free to work on it @egordorichev I'm still working on the code/sfx editor and I have less free time now

**Comment by egordorichev** [comment]
Oh, you are adding editors? Nice :) Will work on that on my free time.

**Comment by hallucino** [comment]
@egordorichev do you want to do it ?

**Comment by egordorichev** [comment]
Ah, really busy with upcoming jams, sorry :(
