### ISSUE TITLE
ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by astearon** [Gigoteur/UnicornConsole#64]
I get this error whenever i try to load anything.

**Comment by hallucino** [comment]
Have you more details ? For windows or linux ?

**Comment by astearon** [comment]
Windows 10 x64.
What other details do you need ? 
Is there a log that i could extract or something ?

**Comment by hallucino** [comment]
Have you python3 installed ?

**Comment by astearon** [comment]
yes i have : Python 3.6.3

**Comment by hallucino** [comment]
for x86-64 ?

**Comment by astearon** [comment]
x86 only.  I installed x64 and the error is gone however i now get this:
[2017-10-30][21:37:54][INFO] [PX8] Loading LUA Plugin
thread 'main' panicked at 'LUA plugin disabled', src\plugins\lua_plugin.rs:2381
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by hallucino** [comment]
Do you use the pre-compiled binary or are you doing your own ?

**Comment by astearon** [comment]
I used the pre-compiled binary
Should i try and compile my own ?

**Comment by hallucino** [comment]
It is really weird ! I don't see why you have this error. Yes you could but I will try to find the reason too

**Comment by LovelyA72** [comment]
![image](https://user-images.githubusercontent.com/29054052/34326002-b974be04-e8dd-11e7-8ae1-fdf5aabebfd6.png)
Same error here...
Windows 10 x64

Debug in VS2015:
![image](https://user-images.githubusercontent.com/29054052/34326012-f87577a6-e8dd-11e7-9456-279987d69da2.png)

Address: 00007fff96e3350e()

> 00007FFF96E3350E  int         29h  
00007FFF96E33510  mov         edx,40000015h  
00007FFF96E33515  mov         ecx,3  
00007FFF96E3351A  call        00007FFF96E31DF8  
00007FFF96E3351F  mov         ecx,3  
00007FFF96E33524  call        00007FFF96E35640  
00007FFF96E33529  int         3  
00007FFF96E3352A  int         3  
00007FFF96E3352B  int         3  
00007FFF96E3352C  int         3  
00007FFF96E3352D  int         3  
00007FFF96E3352E  int         3  
00007FFF96E3352F  int         3  
00007FFF96E33530  lea         rax,[7FFF96EA69D0h]  
00007FFF96E33537  ret  
00007FFF96E33538  int         3  
00007FFF96E33539  int         3  
00007FFF96E3353A  int         3  
00007FFF96E3353B  int         3  
00007FFF96E3353C  int         3  
00007FFF96E3353D  int         3  
00007FFF96E3353E  int         3  
00007FFF96E3353F  int         3  
00007FFF96E33540  lea         rax,[7FFF96EA7440h]  
00007FFF96E33547  ret  
00007FFF96E33548  int         3  
00007FFF96E33549  int         3  
00007FFF96E3354A  int         3  
00007FFF96E3354B  int         3  
00007FFF96E3354C  int         3
