### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by Melon-Bread** [Gigoteur/UnicornConsole#67]
If you follow the README.md it says to:

> cd unicorn-devkit
> cargo build --release

Yet when you run that you are greeted with this:

> error: failed to parse manifest at `C:\Users\melon\Documents\GitHub\UnicornConsole\unicorn-devkit\Cargo.toml`
>
> Caused by:
>  no targets specified in the manifest
> either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present

So I do not know if I am missing something or the build instructions just need updated,

**Comment by hallucino** [comment]
Weird !! Are you sync with the latest commit ?

**Comment by hallucino** [comment]
Ok my bad I forgot to push a file :)

Could you try now ?

**Comment by Melon-Bread** [comment]
Yup works perfect now. Thank you so much!
